### ISSUE TITLE
Music Playback Error when Proxying with Authentication

### ISSUE THREAD

**Issue by oakesville** [oakesville/mythling#55]
When proxying through Apache with digest auth (as for external access), music playback fails with the following exception on Lollipop (works on 4.0.4).  Seems to fail with external player preference setting as well.  See also #53.

<pre>
QCMediaPlayer could not be located....
QCMediaPlayer mediaplayer NOT present
setDataSource IOException happend : 
java.io.FileNotFoundException: No content provider: http://mythling:xxxxxxx@174.29.98.144:8989/Content/GetMusic?Id=16414
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1074)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:927)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:854)
at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1087)
at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1061)
at com.oakesville.mythling.MusicPlaybackService.onStartCommand(MusicPlaybackService.java:119)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3307)
at android.app.ActivityThread.access$2200(ActivityThread.java:177)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5942)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
</pre>

**Comment by oakesville** [comment]
Fixed by MediaStreamProxy.
